export interface VocabularyCard {
  id: string;
  chapter: number;
  kind: "verb" | "noun";
  prompt: string;
  arabic: string;
  target: string;
  answer: string;
  detail: string;
  translation?: string;
  singular?: string;
  plural?: string;
  forms?: {
    past?: string;
    present?: string;
    command?: string;
    masdar?: string;
  };
  requiredPreposition?: string;
}

export const vocabularyCards: VocabularyCard[] = [
  {
    id: "ch1-verb-look",
    chapter: 1,
    kind: "verb",
    prompt: "What does the highlighted verb mean?",
    arabic: "أَنَا أَنْظُرُ إِلَى الْكِتَابِ",
    target: "أَنْظُرُ",
    answer: "to look at",
    detail: "Learn the verb with its required preposition.",
    translation: "I look at the book.",
    forms: { past: "نَظَرَ", present: "يَنْظُرُ", command: "اُنْظُرْ", masdar: "نَظَر" },
    requiredPreposition: "إِلَى",
  },
  {
    id: "ch1-verb-listen",
    chapter: 1,
    kind: "verb",
    prompt: "Which action is happening here?",
    arabic: "أَسْتَمِعُ إِلَى الْأُسْتَاذِ",
    target: "أَسْتَمِعُ",
    answer: "to listen to",
    detail: "This verb also takes إِلَى.",
    translation: "I listen to the teacher.",
    forms: {
      past: "اِسْتَمَعَ",
      present: "يَسْتَمِعُ",
      command: "اِسْتَمِعْ",
      masdar: "اِسْتِمَاع",
    },
    requiredPreposition: "إِلَى",
  },
  {
    id: "ch1-verb-repeat",
    chapter: 1,
    kind: "verb",
    prompt: "What does this verb family mean?",
    arabic: "أُعِيدُ السُّؤَالَ",
    target: "أُعِيدُ",
    answer: "to repeat",
    detail: "Past: أَعَادَ. Present: يُعِيدُ.",
    translation: "I repeat the question.",
    forms: { past: "أَعَادَ", present: "يُعِيدُ", command: "أَعِدْ", masdar: "إِعَادَة" },
  },
  {
    id: "ch1-verb-read",
    chapter: 1,
    kind: "verb",
    prompt: "What does the highlighted verb mean?",
    arabic: "أَقْرَأُ كِتَابًا",
    target: "أَقْرَأُ",
    answer: "to read",
    detail: "Past: قَرَأَ. Masdar: قِرَاءَة.",
    translation: "I read a book.",
    forms: { past: "قَرَأَ", present: "يَقْرَأُ", command: "اِقْرَأْ", masdar: "قِرَاءَة" },
  },
  {
    id: "ch1-noun-book",
    chapter: 1,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا كِتَابٌ",
    target: "كِتَابٌ",
    answer: "book",
    detail: "Plural: كُتُبٌ.",
    translation: "This is a book.",
    singular: "كِتَابٌ",
    plural: "كُتُبٌ",
  },
  {
    id: "ch1-noun-student",
    chapter: 1,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا طَالِبٌ",
    target: "طَالِبٌ",
    answer: "student",
    detail: "Plural: طُلَّابٌ.",
    singular: "طَالِبٌ",
    plural: "طُلَّابٌ",
  },
  {
    id: "ch1-noun-language",
    chapter: 1,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذِهِ لُغَةٌ",
    target: "لُغَةٌ",
    answer: "language",
    detail: "Plural: لُغَاتٌ.",
    singular: "لُغَةٌ",
    plural: "لُغَاتٌ",
  },
  {
    id: "ch1-noun-teacher",
    chapter: 1,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هُوَ مُدَرِّسٌ",
    target: "مُدَرِّسٌ",
    answer: "teacher",
    detail: "Plural: مُدَرِّسُونَ.",
    singular: "مُدَرِّسٌ",
    plural: "مُدَرِّسُونَ",
  },
  {
    id: "ch1-noun-doctor",
    chapter: 1,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هُوَ طَبِيبٌ",
    target: "طَبِيبٌ",
    answer: "doctor",
    detail: "Plural: أَطِبَّاءُ.",
    singular: "طَبِيبٌ",
    plural: "أَطِبَّاءُ",
  },
  {
    id: "ch1-noun-question",
    chapter: 1,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا سُؤَالٌ",
    target: "سُؤَالٌ",
    answer: "question",
    detail: "Plural: أَسْئِلَةٌ.",
    singular: "سُؤَالٌ",
    plural: "أَسْئِلَةٌ",
  },
  {
    id: "ch2-noun-family",
    chapter: 2,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذِهِ أُسْرَةٌ",
    target: "أُسْرَةٌ",
    answer: "family",
    detail: "Plural: أُسَرٌ.",
    singular: "أُسْرَةٌ",
    plural: "أُسَرٌ",
  },
  {
    id: "ch2-noun-father",
    chapter: 2,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا أَبٌ",
    target: "أَبٌ",
    answer: "father",
    detail: "Plural: آبَاءُ.",
    singular: "أَبٌ",
    plural: "آبَاءُ",
  },
  {
    id: "ch2-noun-mother",
    chapter: 2,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذِهِ أُمٌّ",
    target: "أُمٌّ",
    answer: "mother",
    detail: "Plural: أُمَّهَاتٌ.",
    singular: "أُمٌّ",
    plural: "أُمَّهَاتٌ",
  },
  {
    id: "ch2-noun-brother",
    chapter: 2,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا أَخٌ",
    target: "أَخٌ",
    answer: "brother",
    detail: "Plural: إِخْوَةٌ / إِخْوَانٌ.",
    singular: "أَخٌ",
    plural: "إِخْوَةٌ / إِخْوَانٌ",
  },
  {
    id: "ch2-noun-sister",
    chapter: 2,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذِهِ أُخْتٌ",
    target: "أُخْتٌ",
    answer: "sister",
    detail: "Plural: أَخَوَاتٌ.",
    singular: "أُخْتٌ",
    plural: "أَخَوَاتٌ",
  },
  {
    id: "ch2-noun-uncle",
    chapter: 2,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا عَمٌّ",
    target: "عَمٌّ",
    answer: "paternal uncle",
    detail: "Plural: أَعْمَامٌ. Keep this separate from عَمَّةٌ.",
    singular: "عَمٌّ",
    plural: "أَعْمَامٌ",
  },
  {
    id: "ch2-noun-aunt",
    chapter: 2,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذِهِ عَمَّةٌ",
    target: "عَمَّةٌ",
    answer: "paternal aunt",
    detail: "Plural: عَمَّاتٌ. This is intentionally near عَمٌّ.",
    singular: "عَمَّةٌ",
    plural: "عَمَّاتٌ",
  },
  {
    id: "ch3-noun-district",
    chapter: 3,
    kind: "noun",
    prompt: "Translate the highlighted noun in this context.",
    arabic: "أَسْكُنُ فِي حَيِّ الْجَامِعَةِ",
    target: "حَيِّ",
    answer: "area, district",
    detail: "Plural: أَحْيَاءُ. In this textbook context it means district, not alive.",
    translation: "I live in the university district.",
    singular: "حَيٌّ",
    plural: "أَحْيَاءُ",
  },
  {
    id: "ch3-noun-house",
    chapter: 3,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا بَيْتٌ",
    target: "بَيْتٌ",
    answer: "house",
    detail: "Plural: بُيُوتٌ.",
    singular: "بَيْتٌ",
    plural: "بُيُوتٌ",
  },
  {
    id: "ch3-noun-apartment",
    chapter: 3,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذِهِ شَقَّةٌ",
    target: "شَقَّةٌ",
    answer: "apartment",
    detail: "Plural: شُقَقٌ.",
    singular: "شَقَّةٌ",
    plural: "شُقَقٌ",
  },
  {
    id: "ch3-noun-university",
    chapter: 3,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذِهِ جَامِعَةٌ",
    target: "جَامِعَةٌ",
    answer: "university",
    detail: "Plural: جَامِعَاتٌ.",
    singular: "جَامِعَةٌ",
    plural: "جَامِعَاتٌ",
  },
  {
    id: "ch5-noun-food",
    chapter: 5,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا طَعَامٌ",
    target: "طَعَامٌ",
    answer: "food",
    detail: "Plural: أَطْعِمَةٌ.",
    singular: "طَعَامٌ",
    plural: "أَطْعِمَةٌ",
  },
  {
    id: "ch5-noun-drink",
    chapter: 5,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا شَرَابٌ",
    target: "شَرَابٌ",
    answer: "drink",
    detail: "Plural: أَشْرِبَةٌ.",
    singular: "شَرَابٌ",
    plural: "أَشْرِبَةٌ",
  },
  {
    id: "ch5-noun-water",
    chapter: 5,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا مَاءٌ",
    target: "مَاءٌ",
    answer: "water",
    detail: "Plural: مِيَاهٌ.",
    singular: "مَاءٌ",
    plural: "مِيَاهٌ",
  },
  {
    id: "ch5-noun-meat",
    chapter: 5,
    kind: "noun",
    prompt: "Translate the highlighted noun.",
    arabic: "هَذَا لَحْمٌ",
    target: "لَحْمٌ",
    answer: "meat",
    detail: "Plural: لُحُومٌ.",
    singular: "لَحْمٌ",
    plural: "لُحُومٌ",
  },
];
